#!/usr/bin/env bash
# install and setup Nginx server


sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER"  /var/www/html/
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start

