#!/usr/bin/env bash
# Configure redirection in nginx

sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
new_lines="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s~server_name _;~$new_lines~" /etc/nginx/sites-enabled/default
sudo service nginx reload
