#!/usr/bin/env bash
# Configure redirection in nginx

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
new_lines="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s~server_name _;~$new_lines~" /etc/nginx/sites-enabled/default
if [[ $(pgrep nginx) ]]
then
	sudo service nginx restart
else
	sudo service nginx start
fi
