#!/usr/bin/env bash
# Script to setup 404 not found on an ubuntu server

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
chown -R "$USER":"$USER"  /var/www/html/
echo "Hello World!" > /var/www/html/index.html
new_lines="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
replace_404="server_name _;\n\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\t root /usr/share/nginx/html; \n\t}"
sed -i "s~server_name _;~$new_lines~" /etc/nginx/sites-enabled/default
sed -i "s~server_name _;~$replace_404~" /etc/nginx/sites-enabled/default
mkdir -p /user/share/nginx/html/
echo "Ceci n'est pas une page" >  /usr/share/nginx/html/404.html
if [[ $(pgrep nginx) ]]
then
	sudo service nginx restart
else
	sudo service nginx start
fi
