#!/usr/bin/env bash
# Configure a new load balancer
frontend="frontend http_fe\n\tbind *:80\n\tdefault_backend my_servers"
backend="backend my_servers\n\tbalance roundrobin\n\tserver 136397-web-01 54.234.93.141:80 check\n\tserver 136397-web-02 34.207.154.98:80 check"
apt-get update -y
apt-get -y install haproxy=2.0.\*
echo -e "$frontend" >>  /etc/haproxy/haproxy.cfg
echo -e "$backend" >>  /etc/haproxy/haproxy.cfg
service haproxy restart
